### PR TITLE
Updated to Angular 16.x

### PR DESCRIPTION
**Pull request by HeinSnyman**

### CODE REVIEW

**Comment by moodyVlad** [comment]
Hey,
Can this be merged?
Eould be extremely useful.

**Comment by TimUnderhay** [comment]
Thanks @HeinSnyman for the PR!  I made a few changes with dependencies and converted it to be a standalone component, though I don't believe that will change how you use it.

@moodyVlad ^^^

**Comment by moodyVlad** [comment]
Thank you Tim!
All the best

**Comment by HeinSnyman** [comment]
Thanks a lot @TimUnderhay!

**Pull request merged**
